name: DevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.1.0
        # uses: dailydotdev/action-devcard@2.0.2
        # uses: dailydotdev/action-devcard@3.0.0
        with:
          # devcard_id: ${{ secrets.DEVCARD_ID }}
          user_id: ${{ secrets.USER_ID }}
          commit_message: "chore: update ${filename}"
